version: '2'
services:
  web:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./log:/log
      - ./cert:/cert
      - ./webapp/dist:/srv
    ports:
      - "2015:2015"
  api:
    build: ./test_api
    image: test_api
    expose:
      - "80"
    networks:
      default :
      database:
        ipv4_address: 192.168.1.2
  signup:
    build: ./signup
    image: signup
    expose:
      - "80"
    networks:
      default :
      database:
        ipv4_address: 192.168.1.5
  db1:
    build: ./db1
    volumes:
      - ./data/db1:/data
      - ./log/db1:/log
      - ./db1/conf:/conf
    networks:
      database:
        ipv4_address: 192.168.1.3
    expose:
      - "28015"
      - "29015"
    ports:
      - "8080:8080"
  db2:
    build: ./db2
    volumes:
      - ./data/db2:/data
      - ./log/db2:/log
      - ./db2/conf:/conf
    networks:
      database:
        ipv4_address: 192.168.1.4
    expose:
      - "28015"
      - "29015"
networks:
  database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/29
          gateway: 192.168.1.1
