version: '2'
services:
  web:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./log:/log
      - ./cert:/cert
      - ./webapp/dist:/srv
    ports:
      - "2015:2015"
  api:
    build: ./test_api
    image: test_api
    expose:
      - "80"
  signup:
    build: ./signup
    image: signup
    expose:
      - "80"
  db:
    image: rethinkdb
    expose:
      - "28015"
      - "29015"
    ports:
      - "8080:8080"
